package com.axiel7.yumehyou.core.model

data class UnifiedMedia(
    val id: String,
    val mediaType: MediaType,
    val canonicalSource: MetadataSource = mediaType.defaultMetadataSource,
    val title: Title,
    val status: MediaStatus? = null,
    val description: String? = null,
    val coverImageUrl: String? = null,
    val bannerImageUrl: String? = null,
    val startDate: PartialDate? = null,
    val endDate: PartialDate? = null,
    val episodeCount: Int? = null,
    val chapterCount: Int? = null,
    val volumeCount: Int? = null,
    val durationMinutes: Int? = null,
    val countryOfOrigin: String? = null,
    val originLanguage: String? = null,
    val contentRating: ContentRating? = null,
    val synonyms: List<String> = emptyList(),
    val genres: List<String> = emptyList(),
    val tags: List<Tag> = emptyList(),
    val staff: List<Staff> = emptyList(),
    val characters: List<Character> = emptyList(),
    val relations: List<Relation> = emptyList(),
    val externalLinks: List<ExternalLink> = emptyList(),
    val trackerMappings: List<TrackerMapping> = emptyList(),
)

data class UnifiedLibraryEntry(
    val mediaId: String,
    val mediaType: MediaType,
    val status: LibraryEntryStatus,
    val score: Score? = null,
    val progress: Int? = null,
    val progressVolumes: Int? = null,
    val repeatCount: Int = 0,
    val startedAt: PartialDate? = null,
    val completedAt: PartialDate? = null,
    val notes: String? = null,
    val isPrivate: Boolean = false,
    val trackerMappings: List<TrackerMapping> = emptyList(),
)
